# Generated by Django 2.0.9 on 2020-05-31 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffer',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('size', models.BigIntegerField(max_length=11, null=True)),
                ('date', models.DateField(max_length=50, null=True)),
                ('path', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'coffer',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('size', models.BigIntegerField(max_length=11, null=True)),
                ('date', models.DateField(max_length=50, null=True)),
                ('path', models.FileField(max_length=255, null=True, upload_to='files/doc')),
            ],
            options={
                'db_table': 'doc',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('size', models.BigIntegerField(max_length=11, null=True)),
                ('date', models.DateField(max_length=50, null=True)),
                ('path', models.FileField(max_length=255, null=True, upload_to='files/img')),
            ],
            options={
                'db_table': 'img',
            },
        ),
        migrations.CreateModel(
            name='Md5',
            fields=[
                ('md5', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'md5',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('size', models.BigIntegerField(max_length=11, null=True)),
                ('date', models.DateField(max_length=50, null=True)),
                ('path', models.FileField(max_length=255, null=True, upload_to='files/radio')),
                ('md5', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Md5')),
            ],
            options={
                'db_table': 'radio',
            },
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('size', models.BigIntegerField(max_length=11, null=True)),
                ('date', models.DateField(max_length=50, null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('md5', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Md5')),
            ],
            options={
                'db_table': 'trash',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('size', models.BigIntegerField(max_length=11, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('size', models.BigIntegerField(max_length=11, null=True)),
                ('date', models.DateField(max_length=50, null=True)),
                ('path', models.FileField(max_length=255, null=True, upload_to='files/videos')),
                ('md5', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Md5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.AddField(
            model_name='trash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='radio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='img',
            name='md5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Md5'),
        ),
        migrations.AddField(
            model_name='img',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='doc',
            name='md5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Md5'),
        ),
        migrations.AddField(
            model_name='doc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='coffer',
            name='md5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Md5'),
        ),
        migrations.AddField(
            model_name='coffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
